server:
  host: "localhost"
  port: 8080
  shutdown_timeout: "30s"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

storage:
  data_dir: "./data"
  max_file_size: 1073741824  # 1GB
  bloom_filter_size: 1000000
  bloom_filter_hash: 7

network:
  enable_tls: false
  cert_file: ""
  key_file: ""
  max_connections: 1000 